# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userother',
            name='phone',
            field=models.CharField(default=110, max_length=50, verbose_name='用户手机'),
        ),
    ]
